# Generated by Django 5.1.1 on 2024-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_proyectos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='estado',
            field=models.CharField(choices=[('en_desarrollo', 'En Desarrollo'), ('terminado', 'Terminado'), ('pausado', 'Pausado'), ('cancelado', 'Cancelado')], default='en_desarrollo', max_length=20),
        ),
    ]
