# Generated by Django 5.0.4 on 2024-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
