# Generated by Django 5.1.1 on 2024-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_proyectos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='descripcion2',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='lenguajes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
