# Generated by Django 5.1.1 on 2024-12-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_proyectos_categoria_proyectos_descripcion2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='descripcion2',
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
