# Generated by Django 5.1.1 on 2024-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_proyectos_descripcion2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
