# Generated by Django 5.1.1 on 2025-02-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_proyectos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='imgs'),
        ),
    ]
