# Generated by Django 5.1.6 on 2025-05-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_proyectos_imagen2_proyectos_imagen3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='descripcion',
        ),
    ]
